# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(967, 881)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        self.grpCamera = QtWidgets.QGroupBox(Form)
        self.grpCamera.setGeometry(QtCore.QRect(20, 20, 661, 521))
        self.grpCamera.setObjectName("grpCamera")
        self.lblImg = QtWidgets.QLabel(self.grpCamera)
        self.lblImg.setGeometry(QtCore.QRect(10, 20, 640, 480))
        self.lblImg.setText("")
        self.lblImg.setObjectName("lblImg")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(700, 20, 251, 521))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 120, 181, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lblStatus = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lblStatus.setObjectName("lblStatus")
        self.horizontalLayout.addWidget(self.lblStatus)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 250, 131, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnOpen = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnOpen.setObjectName("btnOpen")
        self.verticalLayout.addWidget(self.btnOpen)
        self.btnClose = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnClose.setObjectName("btnClose")
        self.verticalLayout.addWidget(self.btnClose)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 550, 931, 321))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.listResult = QtWidgets.QListWidget(self.groupBox_2)
        self.listResult.setGeometry(QtCore.QRect(3, 20, 451, 291))
        self.listResult.setObjectName("listResult")
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.tableLeft = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableLeft.setGeometry(QtCore.QRect(6, 20, 451, 291))
        self.tableLeft.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableLeft.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableLeft.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableLeft.setObjectName("tableLeft")
        self.tableLeft.setColumnCount(3)
        self.tableLeft.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableLeft.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableLeft.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableLeft.setHorizontalHeaderItem(2, item)
        self.tableLeft.horizontalHeader().setCascadingSectionResizes(True)
        self.tableLeft.horizontalHeader().setDefaultSectionSize(126)
        self.tableLeft.horizontalHeader().setStretchLastSection(True)
        self.tableLeft.verticalHeader().setVisible(False)
        self.tableLeft.verticalHeader().setHighlightSections(False)
        self.horizontalLayout_2.addWidget(self.groupBox_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "售货机"))
        self.grpCamera.setTitle(_translate("Form", "摄像头画面"))
        self.groupBox.setTitle(_translate("Form", "柜门状态"))
        self.label.setText(_translate("Form", "当前状态："))
        self.lblStatus.setText(_translate("Form", "关"))
        self.btnOpen.setText(_translate("Form", "开门"))
        self.btnClose.setText(_translate("Form", "关门"))
        self.groupBox_2.setTitle(_translate("Form", "识别结果"))
        self.groupBox_3.setTitle(_translate("Form", "柜子剩余"))
        item = self.tableLeft.horizontalHeaderItem(0)
        item.setText(_translate("Form", "classid"))
        item = self.tableLeft.horizontalHeaderItem(1)
        item.setText(_translate("Form", "商品名"))
        item = self.tableLeft.horizontalHeaderItem(2)
        item.setText(_translate("Form", "数量"))
